language: python

#List the versions of python to test against
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

branches:
  only:
    - master

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install pep8 sphinx --use-mirrors
  - pip install coveralls
  - pip install -e .

script:
  # Validate PEP8 compliance
  - pep8 -r  --statistics  --count pytvdbapi/

  # Test the examples in the README file
  - python -m doctest -v README.rst

  # Run all unittests and doctests
  - coverage run setup.py test
  - coverage report -m

  # Test that the documentation is working
  - cd docs/source/
  - sphinx-build -W -b html -d /tmp/doctrees .  /tmp/html
  - sphinx-build -W -b linkcheck -d /tmp/doctrees .  /tmp/linkcheck

after_success:
  - coveralls

notifications:
  email:
    - develop@bjornlarsson.net
